### ISSUE TITLE
Fix the error message that is thrown by the assignment solver

### ISSUE THREAD

**Issue by konnov** [konnov/apalache#104]
Currently, when some variables are not assigned, the model checker throws a scary exception:

```
(This should not have happened, but it did. REPORT IT: [https://github.com/konnov/apalache/issues],at.forsyte.apalache.tla.assignments.AssignmentException: Failed to find assignments and symbolic transitions in Next)
Unhandled exception                                               E@20:55:26.454
at.forsyte.apalache.tla.assignments.AssignmentException: Failed to find assignments and symbolic transitions in Next
```

We should print a comprehensible message and guide the user to fix the assignments.

**Comment by lemmy** [comment]
FWIW: Most wording of TLC can be found in [MP.java](https://github.com/tlaplus/tlaplus/blob/1c920e111b0ad5eb2d2b488080db72653cff2250/tlatools/src/tlc2/output/MP.java#L324-L1312).

**Comment by konnov** [comment]
The first fix is in the unstable branch. The tool produces a normal error instead of an unhandled exception. A better diagnostics will require some effort, so it goes in #111.
