### ISSUE TITLE
TlaExBuilder

### ISSUE THREAD

**Issue by konnov** [konnov/apalache#13]
Currently, one has to construct TLAEx objects using a variety of operators found in different classes, e.g., ```OperEx(TlaBoolOper.not, ...)``` and ```OperEx(TlaOper.eq, ...)```.

Let's add an object ```TlaExBuilder``` that contains handy constructors for all possible combinations of expressions in LIR.

**Comment by Kukovec** [comment]
All methods, total test coverage.
