### ISSUE TITLE
Fix LetInOper

### ISSUE THREAD

**Issue by Kukovec** [konnov/apalache#14]
needs proper constructor and equality check methods, consider migrating to TlaControlOper inner class.

**Comment by konnov** [comment]
The current idea is to remove `LetInOper` from the set of operators. Indeed, it looks more like a declaration rather than an operator. Instead, we will introduce a subclass of `TlaEx` that contains `TlaOperDecl` as an argument.

**Comment by konnov** [comment]
Commit 3244b15 introduces `LetIn0Ex`, which is a special case of the expression discussed in this issue. Shall we introduce a full version, e.g., `LetInEx` that would replace both `LetIn0Ex` and `LetInOper'? Then the preprocessing would expand all the let definitions that have parameters and leave the nullary definitions.

**Comment by Kukovec** [comment]
After a lot of back-and-forth, we've decided to drop `LetIn0Ex` and introduce a uniform `LetInEx` instead of `LetInOper`. In a future commit, LET-IN expansion will be modified to optionally avoid expanding 0-arity operators.
