### ISSUE TITLE
[BUG] rewriter error: SubstRule: Variable t_9 is not assigned a value

### ISSUE THREAD

**Issue by andrey-kuprianov** [konnov/apalache#141]
**Describe the bug**
The error encountered when checking https://github.com/konnov/apalache-tests/blob/master/parametric/SetSndRcv/SetSndRcv_NoFullDropCard_5.tla

The following exception is thrown:
`at.forsyte.apalache.tla.bmcmt.RewriterException: SubstRule: Variable t_9 is not assigned a value)`

The error is related to set cardinalities, because https://github.com/konnov/apalache-tests/blob/master/parametric/SetSndRcv/SetSndRcv_NoFullDrop_15.tla is checked without problems.

**To Reproduce**
`~/tools/apalache/bin/apalache-mc check SetSndRcv_NoFullDropCard_5.tla`

**Log files**
[detailed.log](https://github.com/konnov/apalache/files/4546237/detailed.log)

**Desktop**
 - OS:  Ubuntu Linux
 - Apalache version: 0.7.0

**Comment by konnov** [comment]
Are you sure that you have the latest version? I get no error on b3fbc9f44647f62fde92f378f0e429dc258e737f:

```Step 10, level 10: checking if 3 transition(s) are enabled and violate the invariant I@16:50:30.876
Step 10, level 11: collecting 3 enabled transition(s)             I@16:50:30.987
The outcome is: NoError                                           I@16:50:31.064
PASS #11: Terminal                                                I@16:50:31.065
Checker reports no error up to computation length 10              I@16:50:31.065
It took me 0 days  0 hours  0 min  3 sec                          I@16:50:31.065
Total time: 3.711 sec                                             I@16:50:31.065
EXITCODE: OK
```

**Comment by andrey-kuprianov** [comment]
Sorry, my bad -- forgot to build the package :(  There is no bug indeed:)
