### ISSUE TITLE
Importer not handling @ shorthand

### ISSUE THREAD

**Issue by Kukovec** [konnov/apalache#15]
On code such as 
`[msgs EXCEPT ![self] = @ \ {q}] `
the importer throws
`at.forsyte.apalache.tla.imp.SanyImporterException: Unexpected subclass of tla2sany.ExprOrOpArgNode: class tla2sany.semantic.AtNode`

**Comment by konnov** [comment]
Fixed, see ExprOrOpArgNodeTranslator.translateAt
