### ISSUE TITLE
Handle operators declared as LOCAL

### ISSUE THREAD

**Issue by Kukovec** [konnov/apalache#49]
Currently there is no support for local operators - the solver throws an importer exception.

**Comment by konnov** [comment]
I have added test("LOCAL operator") in TestSanyImporter. It goes through. Do you have an example?

**Comment by konnov** [comment]
Finally, we have a sound fix now. Thanks to the elegant solution proposed by @Kukovec.

Every use of a LOCAL operator `F(...)` is replaced with a local LET-IN definition `LET F(...) = ... IN F(...)`.
