### ISSUE TITLE
TlaUserOper vs TlaOper.apply

### ISSUE THREAD

**Issue by Kukovec** [konnov/apalache#55]
Currently, we have 2 ways of representing operator application, `TlaOper.apply`, which the parser only uses in higher-order operators and `TlaUserOper`, used when calling predefined operators. We should consider having only one way to represent operator application: `TlaOper.apply`. `TlaUserOper` is, in my opinion, too rich, as it carries with it the full declaration of the operator being applied (the declaration is never used anywhere).

Example:
```
B(p) == 0
A(X(_)) == X(0) + B(0)
```
The expressions `X(0)` and `B(0)` have different internal representations.

**Comment by konnov** [comment]
Let's use `TlaOper.apply` instead of `TlaUserOper`. It will be closer in spirit of `NameEx(...)`.
