### ISSUE TITLE
TrivialTypeFinder assertion violated

### ISSUE THREAD

**Issue by Kukovec** [konnov/apalache#63]
The module
```
VARIABLE x

Init == x = 0
Next == UNCHANGED x

P == \A j \in {} : TRUE

InvFail == TRUE <=> P
InvOk1 == P
InvOk2 == ( TRUE => P ) /\ ( P => TRUE )
```
fails when called with `--inv=InvFail` (`TrivialTypeFinder` throws an exception), but succeeds with `--inv=InvOkX` for `X = 1,2`.

The cause of this is the `toNegatedForm` transformation of `<=>`, which introduces 2 copies of `\A`-bound variables with the same name.

Suggestion: SimpleSkolemization::toNegatedForm needs to happen before renaming or there needs to be an additional renaming step afterwards.

**Comment by konnov** [comment]
Fixed that, but code review led to new bugs discovered
