### ISSUE TITLE
Split SimpleSkolemization.transformAndLabel

### ISSUE THREAD

**Issue by konnov** [konnov/apalache#65]
into two methods: `transform` and `label`, so we can do renaming right after `transform`. And rename `label` in `markExistentials`.

**Comment by Kukovec** [comment]
No need, `transformAndLabel` makes two calls, one to `toNegatedForm`, (transform) and one to `markFreeExistentials` (label). All that's needed is a call to `Renaming::renameBindingsUnique` in between.
