### ISSUE TITLE
Parse TLC configuration files

### ISSUE THREAD

**Issue by konnov** [konnov/apalache#76]
Apalache supports two approaches to dealing with constants: (1) asking the user to overwrite them with constant definitions, and (2) declaring a `ConstInit` operator that restricts the constants. The both approaches are incompatible with automation.

We should take the approach of TLC and simply parse the TLC config files.

**Comment by lemmy** [comment]
In reverse, we want TLC to support something like ```ConstInit```: https://github.com/tlaplus/tlaplus/issues/272

**Comment by andrey-kuprianov** [comment]
implemented with the last commit a7028ba
