### ISSUE TITLE
Print timestamp when moving to next step

### ISSUE THREAD

**Issue by lemmy** [konnov/apalache#88]
To better track progress, apalache should include a timestamp when it moves to the next step.

```
Worker 1: Step 0, level 0: collecting 1 enabled transition(s)       I@092204.370
Worker 1: Step 1, level 0: collecting 2 enabled transition(s)       I@092204.890
```

vs

```
Worker 1: Step 0, level 0: collecting 1 enabled transition(s) at 04:23:42      I@092204.370
Worker 1: Step 1, level 0: collecting 2 enabled transition(s) at 04:23:53      I@092204.890
```

**Comment by konnov** [comment]
Do you mean that the timestamp on the right, e.g., `I@092204.370`, is showing the time different from what you like to see?

**Comment by lemmy** [comment]
It didn't occur to me that ```I@092204.370``` is a timestamp. :-)

**Comment by konnov** [comment]
I was trying to keep the logging timestamps as short as possible. I guess, adding two colons in the format will not hurt.
